export const SCREEN_COMMON = {
  MENU: {
    CATCH_ALL: '/:catchAll(.*)',
    ADMIN: '/admin',
    CLIENT: '/client',
    DASHBOARD: 'dashboard',
    ACCOUNT_BALANCE: 'account-balance',
    ACCOUNT_USAGE_FEE: 'account-usage-fee',
    BANK_LIST: 'bank',
    BANK_ADD: 'bank/add',
    BANK_EDIT: 'bank/edit/:id',
    ACCOUNT_LIST: 'account',
    ACCOUNT_ADD: 'account/add',
    ACCOUNT_EDIT: 'account/edit/:id',
    INTRODUCER_LIST: 'introducer',
    INTRODUCER_ADD: 'introducer/add',
    INTRODUCER_EDIT: 'introducer/edit/:id',
    CLIENT_LIST: 'client-list',
    CLIENT_ADD: 'client-list/add',
    CLIENT_EDIT: 'client-list/edit/:id',
    CONTRACTOR_LIST: 'contractor',
    CONTRACTOR_ADD: 'contractor/add',
    CONTRACTOR_EDIT: 'contractor/edit/:id',
    ACCOUNT_CONTRACTOR_LIST: 'account-contractor',
    ACCOUNT_CONTRACTOR_ADD: 'account-contractor/add',
    ACCOUNT_CONTRACTOR_EDIT: 'account-contractor/edit/:id',
    EXPENSE_LIST: 'expense',
    EXPENSE_ADD: 'expense/add',
    EXPENSE_EDIT: 'expense/edit/:id',
    CONTRACT_DETAIL_LIST: 'contract-detail/:id',
    CONTRACT_DETAIL_ADD: 'contract-detail/add/:id',
    CONTRACT_DETAIL_EDIT: 'contract-detail/edit/:id',
    BALANCE_MANAGER: 'balance-manager',
    BLANK: 'blank',
    CHART: 'chart',
    DEMO: 'demo',
    BALANCE_INVOICE: 'balance-invoice',
    CHARGE_HISTORY: 'charge_history',
    AUTH: '/auth',
    LOGIN: 'login',
    LOGIN_BUTTON: '/login',
    _404: '/404',
    NOT_FOUND_SIMPLE: 'not-found-simple',
    ACTION_LOG: 'action-log',
    LOG_TASK: 'log-task',
  },
  MENU_NAME: {
    ADMIN: 'admin',
    CLIENT: 'client',
    DASHBOARD: 'dashboard',
    SETTINGS: 'settings',
    ACCOUNT_BALANCE: 'account-balance',
    ACCOUNT_USAGE_FEE: 'account-usage-fee',
    BANK_LIST: 'bank',
    BANK_ADD: 'bank_add',
    BANK_EDIT: 'bank_edit',
    ACCOUNT_LIST: 'account',
    ACCOUNT_ADD: 'account_add',
    ACCOUNT_EDIT: 'account_edit',
    INTRODUCER_LIST: 'introducer',
    INTRODUCER_ADD: 'introducer_add',
    INTRODUCER_EDIT: 'introducer_edit',
    CLIENT_LIST: 'client-list',
    CLIENT_ADD: 'client-list_add',
    CLIENT_EDIT: 'client-list_edit',
    CONTRACTOR_LIST: 'contractor',
    CONTRACTOR_ADD: 'contractor_add',
    CONTRACTOR_EDIT: 'contractor_edit',
    ACCOUNT_CONTRACTOR_LIST: 'account-contractor',
    ACCOUNT_CONTRACTOR_ADD: 'account-contractor_add',
    ACCOUNT_CONTRACTOR_EDIT: 'account-contractor_edit',
    EXPENSE_LIST: 'expense',
    EXPENSE_ADD: 'expense_add',
    EXPENSE_EDIT: 'expense_edit',
    CONTRACT_DETAIL_LIST: 'client-list_contract_detail',
    CONTRACT_DETAIL_ADD: 'client-list_contract_detail_add',
    CONTRACT_DETAIL_EDIT: 'client-list_contract_detail_edit',
    BALANCE_MANAGER: 'balance-manager',
    BLANK: 'blank',
    CHART: 'chart',
    DEMO: 'demo',
    CLIENT_DASHBOARD: 'client-dashboard',
    CLIENT_BALANCE_INVOICE: 'client-balance-invoce',
    CLIENT_CHARGE_HISTORY: 'client-charge-history',
    CLIENT_BALANCE_MANAGER: 'client-balance-manager',
    LOGIN_BUTTON: 'login-button',
    ACTION_LOG: 'action-log',
    LOG_TASK: 'log-task',
  },
  ACCOUNT: {
    LIST: '/admin/account',
    CREATE: '/accounts/add',
    EDIT: '/accounts',
  },
  CLIENT: {
    LIST: '/admin/client-list',
    EDIT: (id: any) => `/admin/client-list/edit/${id}`,
    CREATE: '/clients',
  },
  INTRODUCER: {
    LIST: '/admin/introducer',
  },
  EXPENSE: {
    LIST: '/admin/expense',
  },
  CONTRACTOR: {
    LIST: '/admin/contractor',
  },
  BANK: {
    LIST: '/admin/bank',
  },
  ACCOUNT_CONTRACTOR: {
    LIST: '/admin/account-contractor',
  },
}
